<a href="https://colab.research.google.com/github/baochuong/Articial-Intelligence-AI-/blob/main/Week3_baitap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
url = 'http://winterolympicsmedals.com/medals.csv'
data = pd.read_csv(url)
data

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
0,1924,Chamonix,Skating,Figure skating,AUT,individual,M,Silver
1,1924,Chamonix,Skating,Figure skating,AUT,individual,W,Gold
2,1924,Chamonix,Skating,Figure skating,AUT,pairs,X,Gold
3,1924,Chamonix,Bobsleigh,Bobsleigh,BEL,four-man,M,Bronze
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold
...,...,...,...,...,...,...,...,...
2306,2006,Turin,Skiing,Snowboard,USA,Half-pipe,M,Silver
2307,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Gold
2308,2006,Turin,Skiing,Snowboard,USA,Half-pipe,W,Silver
2309,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,M,Gold
2310,2006,Turin,Skiing,Snowboard,USA,Snowboard Cross,W,Silver

In [2]:
data[(data['NOC']=='USA') & (data['Medal']=='Gold') & (data['Event']=='individual')]

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
86,1928,St. Moritz,Bobsleigh,Skeleton,USA,individual,M,Gold
246,1948,St. Moritz,Skating,Figure skating,USA,individual,M,Gold
311,1952,Oslo,Skating,Figure skating,USA,individual,M,Gold
386,1956,Cortina d'Ampezzo,Skating,Figure skating,USA,individual,M,Gold
388,1956,Cortina d'Ampezzo,Skating,Figure skating,USA,individual,W,Gold
462,1960,Squaw Valley,Skating,Figure skating,USA,individual,M,Gold
464,1960,Squaw Valley,Skating,Figure skating,USA,individual,W,Gold
674,1968,Grenoble,Skating,Figure skating,USA,individual,W,Gold
887,1976,Innsbruck,Skating,Figure skating,USA,individual,W,Gold
1119,1984,Sarajevo,Skating,Figure skating,USA,individual,M,Gold
1257,1988,Calgary,Skating,Figure skating,USA,individual,M,Gold
1428,1992,Albertville,Skating,Figure skating,USA,individual,W,Gold
1815,1998,Nagano,Skating,Figure skating,USA,individual,W,Gold
2028,2002,Salt Lake City,Bobsleigh,Skeleton,USA,individual,M,Gold
2029,2002,Salt Lake City,Bobsleigh,Skeleton,USA,individual,W,Gold
2037,2002,Salt Lake City,Skating,Figure skating,USA,individual,W,Gold

In [4]:
datas=data[(data['NOC'] =='CAN')]
print("Sá»‘ huy chÆ°Æ¡ng cá»§a CAN:",datas['Medal'].count())
data1=data[(data['Event'] =='individual') & (data['Medal']=='Gold')] 
print("Sá»‘ huy chÆ°Æ¡ng chÆ°Æ¡ng vÃ ng theo mÃ´n cÃ¡ nhÃ¢n:",data1['Event'].count())

Sá»‘ huy chÆ°Æ¡ng cá»§a CAN: 119
Sá»‘ huy chÆ°Æ¡ng chÆ°Æ¡ng vÃ ng theo mÃ´n cÃ¡ nhÃ¢n: 65